### ISSUE TITLE
where'd u go friend

### ISSUE THREAD

**Issue by voqz** [lap00zza/Assistant#1]
we miss u, (the lapzbot team) ): come back boss, or atleast hmu on ur new discord account it's 

> Luxory#0018

**Comment by lap00zza** [comment]
Hey @voqz sorry for leaving without prior notice. But I had some personal reasons. These days I mostly use discord for work. When I get free, I will send you my new discord account.

**Comment by voqz** [comment]
ok well you can always join the new [lapzbot server](https://discord.gg/H2S7h2X) or w.e to hang out or somethin
